### ISSUE TITLE
Many commands return a not found.

### ISSUE THREAD

**Issue by dyerrington** [stolenvw/Discord-Valheim_Bot#4]
![image](https://user-images.githubusercontent.com/2257834/211243507-44baef6c-f72d-49f0-a950-a6996ef73041.png)

Any ideas?

**Comment by stolenvw** [comment]
Stats command was removed, all others were moved to slash commands. (Ie: /active) is there any errors in the log file in the logs dir

**Comment by dyerrington** [comment]
I've tried to reproduce these cases again and after re-running the bot, I can't seem to do it.

These are the steps I've used to reproduce these errors:
- Create virtual env with requirements.txt
- Setup MySQL database 
- Edit config.py file
- Change to `code` directory
- Run `python3 valheimbot.py`
- Initiate slash commands from Discord

Here you can see the commands that I've tried.

![image](https://user-images.githubusercontent.com/2257834/211384270-dd4a5719-9087-4c8c-abbe-c48b4af8f228.png)

After running the bot with the above steps, I see one error in the console:

```bash
2023-01-09 19:44:57 ERROR    discord.ext.tasks Unhandled exception in internal background task 'serveronline'.
Traceback (most recent call last):
  File "/home/dave/discord/Discord-Valheim_Bot/code/utils/mainbot.py", line 471, in serveronline
    if a2s.info(config.SERVER_ADDRESS) and not self.sonline:
  File "/home/dave/.local/lib/python3.8/site-packages/a2s/info.py", line 182, in info
    return request_sync(address, timeout, encoding, InfoProtocol)
  File "/home/dave/.local/lib/python3.8/site-packages/a2s/a2s_sync.py", line 22, in request_sync
    response = request_sync_impl(conn, encoding, a2s_proto)
  File "/home/dave/.local/lib/python3.8/site-packages/a2s/a2s_sync.py", line 28, in request_sync_impl
    resp_data = conn.request(a2s_proto.serialize_request(challenge))
  File "/home/dave/.local/lib/python3.8/site-packages/a2s/a2s_sync.py", line 92, in request
    return self.recv()
  File "/home/dave/.local/lib/python3.8/site-packages/a2s/a2s_sync.py", line 67, in recv
    packet = self._socket.recv(65535)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dave/.local/lib/python3.8/site-packages/discord/ext/tasks/__init__.py", line 239, in _loop
    await self.coro(*args, **kwargs)
  File "/home/dave/discord/Discord-Valheim_Bot/code/utils/mainbot.py", line 480, in serveronline
    await channel.edit(
AttributeError: 'NoneType' object has no attribute 'edit'
```
Looking at the database, it doesn't look like anything is really being logged.  I don't see notifications pointed back at the channel for events like deaths or special events that show up like trolls like you have in your screenshots.

Also, for the dbupdates, it's not clear if these should run on a scheduler or what?  

> "Move to the code dir and run python3 eventsdbupdate.py to update the events database with new events."

The file `eventsdbupdate.py` is not actually in `./code`.  When I run this file from the command line, it gives me:

```bash
$ cd dbupdates/
$ python3 eventsdbupdate.py
Traceback (most recent call last):
  File "eventsdbupdate.py", line 3, in <module>
    from config import SQL_HOST as MYhost
ModuleNotFoundError: No module named 'config'
```

I've let the bot run for several hours while several people logged in doing stuff.  Looks like no stats are collected or events logged for anyone.

**Comment by stolenvw** [comment]
The dbupdates only needs running once, they update the mysql db with added columns and data (dont need to run them at all if its a fresh install and ran the dbsetup.py)

the `socket.timeout: timed out error`, is from it not being able to connect to the server,  if running the server with public = 0, this will happen or if wrong ip port is set in the config for SERVER_ADDRESS

does the logfile you set for `file = `  in the config show people logging in and out of the server during the time the bot was running?

Also check the log in the logs dir, most warnings from my code go there and not to console

**Comment by dyerrington** [comment]
My server is public it seems.  Here are the params for it running:
![image](https://user-images.githubusercontent.com/2257834/211407350-0dda0d41-4db0-4d3b-8ca4-cff93911506c.png)

Also, the port seems to respond (game port + 1):

```bash
$ sudo nmap -p6143 64.31.8.58
Starting Nmap 7.80 ( https://nmap.org ) at 2023-01-09 21:28 CET
Nmap scan report for 58-8-31-64.static.reverse.lstn.net (64.31.8.58)
Host is up (0.15s latency).

PORT     STATE    SERVICE
6143/tcp filtered watershed-lm

Nmap done: 1 IP address (1 host up) scanned in 1.63 seconds
```

Seems like it returns the version just fine.

The same cases from Discord I ran (see prior screenshot), give me this output from the logs (debug level of logging):
```bash
dave@DESKTOP-6M2LH5S:~/discord/Discord-Valheim_Bot/code/logs$ tail -f valheimbot.log
2023-01-09 21:49:16 - INFO - __main__: Synced slash commands for valheim-bot#1588
2023-01-09 21:49:16 - INFO - discord.gateway: Shard ID None has connected to Gateway (Session ID: 6282dccb4db681e49c8682cf29415aa2).
2023-01-09 21:49:18 - INFO - utils.mainbot: Valheim Discord Bot V2.0
2023-01-09 21:49:18 - INFO - utils.mainbot: Bot connected as valheim-bot#1588
2023-01-09 21:49:18 - INFO - utils.mainbot: Command prefix: !
2023-01-09 21:49:18 - INFO - utils.mainbot: Log channel: #valheim
2023-01-09 21:49:18 - INFO - utils.mainbot: VoIP channel: None
2023-01-09 21:49:18 - INFO - utils.mainbot: Main loop started
2023-01-09 21:49:18 - INFO - utils.mainbot: Server online loop started
2023-01-09 21:49:18 - INFO - utils.mainbot: Server verion check loop started
2023-01-09 21:51:00 - ERROR - botcmds.explorecmds: Did not find total locations in the database, Please restart server with bot running.
2023-01-09 21:51:00 - ERROR - botcmds.explorecmds: An error occurred! User: dyerrington, Command 'explored' raised an exception: IndexError: list index out of range
2023-01-09 21:51:21 - ERROR - botcmds.explorecmds: Did not find total locations in the database, Please restart server with bot running.
2023-01-09 21:51:21 - ERROR - botcmds.explorecmds: An error occurred! User: dyerrington, Command 'explored' raised an exception: IndexError: list index out of range
2023-01-09 21:51:31 - ERROR - botcmds.maincmd: ERROR: Join code missing from database
2023-01-09 21:52:26 - ERROR - botcmds.maincmd: CheckFailure from command savestats, User: dyerrington, You are missing at least one of the required roles: '('Admin', 'Mod')'
```

Also, the `eventsdbupdate.py` script still doesn't work as described in your documentation.
![image](https://user-images.githubusercontent.com/2257834/211406353-de886fe0-03ad-4c42-84dc-68c705af5b8c.png)

Just trying to be helpful on that last point rather than file a new bug report.

**Comment by dyerrington** [comment]
Also, this fundamental use case with `a2s` library seems to return something just fine for what it's worth.

```python
>>> import a2s
>>> address = ("64.31.8.58", 6143)
>>> a2s.info(address)
SourceInfo(protocol=17, server_name='<color=#ff7b00>Filthy Monkeys Community Server</color>', map_name='<color=#ff7b00>Filthy Monkeys C', folder='valheim', game='', app_id=0, player_count=1, max_players=64, bot_count=0, server_type='d', platform='w', password_protected=True, vac_enabled=False, version='1.0.0.0', edf=177, port=6142, steam_id=90168008959974406, stv_port=None, stv_name=None, keywords='0.212.9', game_id=892970, ping=0.17575340000075812)
```

**Comment by stolenvw** [comment]
the error might be from the `VoIP channel: None`  do you have `USEVCSTATS = True`  the serveronline loop, does 2 things if `USEVCSTATS` is set to true.  One of the things is to update the channel name of the `VCHANNEL_ID`  by the log that channel is set to None.

the 3 scripts in dbupdates dir i plain on removing and making the dbsetup.py do the changes on the db for the version updates on the bot. (all scripts in dbupdates only change structure of the DB or add info the bot uses, they dont pull any info from your log or server. ) 

the eventsdbupdate.py was added after a valheim update that added a Bats event, to add that event to the db for people that had the bot installed before that. (it was not in the original dbsetup.py)

**Comment by stolenvw** [comment]
updated the mainbot.py with a check to see if VCHANNEL_ID is set to a real channel when USEVCSTATS is set to true.  If VCHANNEL_ID is not a real channel disables the usevcstats in the serveronline loop fixing the error below for happening 
```shell
2023-01-09 19:44:57 ERROR    discord.ext.tasks Unhandled exception in internal background task 'serveronline'.
Traceback (most recent call last):
  File "/home/dave/discord/Discord-Valheim_Bot/code/utils/mainbot.py", line 471, in serveronline
    if a2s.info(config.SERVER_ADDRESS) and not self.sonline:
  File "/home/dave/.local/lib/python3.8/site-packages/a2s/info.py", line 182, in info
    return request_sync(address, timeout, encoding, InfoProtocol)
  File "/home/dave/.local/lib/python3.8/site-packages/a2s/a2s_sync.py", line 22, in request_sync
    response = request_sync_impl(conn, encoding, a2s_proto)
  File "/home/dave/.local/lib/python3.8/site-packages/a2s/a2s_sync.py", line 28, in request_sync_impl
    resp_data = conn.request(a2s_proto.serialize_request(challenge))
  File "/home/dave/.local/lib/python3.8/site-packages/a2s/a2s_sync.py", line 92, in request
    return self.recv()
  File "/home/dave/.local/lib/python3.8/site-packages/a2s/a2s_sync.py", line 67, in recv
    packet = self._socket.recv(65535)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dave/.local/lib/python3.8/site-packages/discord/ext/tasks/__init__.py", line 239, in _loop
    await self.coro(*args, **kwargs)
  File "/home/dave/discord/Discord-Valheim_Bot/code/utils/mainbot.py", line 480, in serveronline
    await channel.edit(
AttributeError: 'NoneType' object has no attribute 'edit'
```

**Comment by dyerrington** [comment]
This is great work.  I'll pull down the latest and try it out tonight and let you know how it goes 👍

**Comment by dyerrington** [comment]
In the spirit of (hopefully) being helpful.  This last update looks like it's produced a few new messages in the logs:

```bash
2023-01-14 22:48:16 - INFO - __main__: Synced slash commands for valheim-bot#1588
2023-01-14 22:48:17 - INFO - discord.gateway: Shard ID None has connected to Gateway (Session ID: d801fb78732d6ccb3f154404da45b489).
2023-01-14 22:48:19 - INFO - utils.mainbot: Valheim Discord Bot V2.0
2023-01-14 22:48:19 - INFO - utils.mainbot: Bot connected as valheim-bot#1588
2023-01-14 22:48:19 - INFO - utils.mainbot: Command prefix: !
2023-01-14 22:48:19 - INFO - utils.mainbot: Log channel: #valheim
2023-01-14 22:48:19 - INFO - utils.mainbot: VoIP channel: None
2023-01-14 22:48:19 - WARNING - utils.mainbot: USEVCSTATS is set to True, but VCHANNEL_ID returns no channel.
2023-01-14 22:48:19 - INFO - utils.mainbot: Main loop started
2023-01-14 22:48:19 - INFO - utils.mainbot: Server online loop started
2023-01-14 22:48:19 - INFO - utils.mainbot: Server verion check loop started
2023-01-14 22:48:20 - ERROR - utils.mainbot: Failed to get version info from server, trying again in 30 minutes.
Traceback (most recent call last):
  File "/home/dave/.local/lib/python3.8/site-packages/mysql/connector/connection_cext.py", line 565, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: Data too long for column 'serverversion' at row 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dave/discord/Discord-Valheim_Bot/code/utils/mainbot.py", line 529, in versioncheck
    mycursor.execute(sql)
  File "/home/dave/.local/lib/python3.8/site-packages/mysql/connector/cursor_cext.py", line 279, in execute
    result = self._cnx.cmd_query(
  File "/home/dave/.local/lib/python3.8/site-packages/mysql/connector/connection_cext.py", line 573, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.DataError: 1406 (22001): Data too long for column 'serverversion' at row 1
```

**Comment by dyerrington** [comment]
Upon inspecting your code, particularly the [mainbot.py](https://github.com/stolenvw/Discord-Valheim_Bot/blob/main/code/utils/mainbot.py) file, it seems the fundamental assumption is that events that are collected come as a result of being able to read a log file.  Is that true?  If so, this isn't really a solution if you have a remote server then is it unless you can stream the logfile somewhere the bot can read like a file handle?

**Comment by stolenvw** [comment]
> Upon inspecting your code, particularly the [mainbot.py](https://github.com/stolenvw/Discord-Valheim_Bot/blob/main/code/utils/mainbot.py) file, it seems the fundamental assumption is that events that are collected come as a result of being able to read a log file. Is that true? If so, this isn't really a solution if you have a remote server then is it unless you can stream the logfile somewhere the bot can read like a file handle?

Like the config says it reads it from the server log file, Valheim servers dont have rcon, or anyway to login to them for getting info.

**Comment by stolenvw** [comment]
> In the spirit of (hopefully) being helpful. This last update looks like it's produced a few new messages in the logs:
> 
> ```shell
> 2023-01-14 22:48:16 - INFO - __main__: Synced slash commands for valheim-bot#1588
> 2023-01-14 22:48:17 - INFO - discord.gateway: Shard ID None has connected to Gateway (Session ID: d801fb78732d6ccb3f154404da45b489).
> 2023-01-14 22:48:19 - INFO - utils.mainbot: Valheim Discord Bot V2.0
> 2023-01-14 22:48:19 - INFO - utils.mainbot: Bot connected as valheim-bot#1588
> 2023-01-14 22:48:19 - INFO - utils.mainbot: Command prefix: !
> 2023-01-14 22:48:19 - INFO - utils.mainbot: Log channel: #valheim
> 2023-01-14 22:48:19 - INFO - utils.mainbot: VoIP channel: None
> 2023-01-14 22:48:19 - WARNING - utils.mainbot: USEVCSTATS is set to True, but VCHANNEL_ID returns no channel.
> 2023-01-14 22:48:19 - INFO - utils.mainbot: Main loop started
> 2023-01-14 22:48:19 - INFO - utils.mainbot: Server online loop started
> 2023-01-14 22:48:19 - INFO - utils.mainbot: Server verion check loop started
> 2023-01-14 22:48:20 - ERROR - utils.mainbot: Failed to get version info from server, trying again in 30 minutes.
> Traceback (most recent call last):
>   File "/home/dave/.local/lib/python3.8/site-packages/mysql/connector/connection_cext.py", line 565, in cmd_query
>     self._cmysql.query(
> _mysql_connector.MySQLInterfaceError: Data too long for column 'serverversion' at row 1
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/dave/discord/Discord-Valheim_Bot/code/utils/mainbot.py", line 529, in versioncheck
>     mycursor.execute(sql)
>   File "/home/dave/.local/lib/python3.8/site-packages/mysql/connector/cursor_cext.py", line 279, in execute
>     result = self._cnx.cmd_query(
>   File "/home/dave/.local/lib/python3.8/site-packages/mysql/connector/connection_cext.py", line 573, in cmd_query
>     raise get_mysql_exception(
> mysql.connector.errors.DataError: 1406 (22001): Data too long for column 'serverversion' at row 1
> ```

Im going assume your running a moded valheim server that has mod info added to the server version.  That is causing this error.

**Comment by stolenvw** [comment]
closing do to age with no comments
